<a href="https://colab.research.google.com/github/maha1606-gitoctocat/Main-Project---Electric-Vehicle-Population-Analysis-using-Python/blob/main/Main_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Electric Vehicle Population Analysis Using Python**

### **Project Objectives**
1. To analyze the distribution of electric vehicles across different geographical regions.

2. To identify the most popular electric vehicle manufacturers and models based on registration data.

3. To examine the trends in electric vehicle adoption over different model years.

4. To compare the performance and characteristics of Battery Electric Vehicles (BEVs) and Plug-in Hybrid Electric Vehicles (PHEVs).

5. To analyze the electric driving range of vehicles and identify factors influencing vehicle performance.

6. To derive meaningful insights from the dataset using data cleaning, exploratory data analysis (EDA), and visualization techniques in Python.

## **Dataset information**

Source : https://catalog.data.gov/dataset/electric-vehicle-population-data

Location : State of Washington

Year/Timeline : June 12, 2026

Domain: Electric Vehicle (EV) / Automotive

# **Stage 1**

# **Business Problem**

As the number of electric vehicles continues to grow, government agencies, utility companies, and automobile manufacturers need to understand EV adoption trends across different regions. However, they often lack clear insights into:

Which counties and cities have the highest EV adoption.

Which manufacturers dominate the EV market.

How electric vehicle range has improved over different model years.

The percentage of vehicles eligible for Clean Alternative Fuel Vehicle (CAFV) incentives.

The distribution of Battery Electric Vehicles (BEVs) versus Plug-in Hybrid Electric Vehicles (PHEVs).

Which electric utility providers serve the largest number of EV owners.

# **Expected Outcome**

The analysis and dashboard should help stakeholders:

Identify the regions with the highest EV registrations.

Determine the top-performing EV manufacturers and models.

Compare the adoption of BEVs and PHEVs.

Analyze trends in electric driving range across model years.

Evaluate CAFV eligibility distribution.

Understand the relationship between EV adoption and electric utility providers.

Support government agencies and utility companies in making data-driven decisions regarding charging station expansion and clean energy initiatives.

# **Dataset Source**

The dataset is an Electric Vehicle (EV) Population Dataset, commonly published as an open public dataset by the Washington State Department of Licensing and distributed through the state's open data portal. It contains information about registered electric vehicles, including vehicle specifications, registration locations, and eligibility for clean fuel incentives.

# **Dataset Size**

**Number of Records (Rows):** 1,999

**Number of Attributes (Columns):** 16

**Dataset Type:** Structured, tabular (CSV)

**Domain:** Transportation / Electric Vehicles

# **Dataset Features**

VIN (Vehicle Identification Number)(1-10)

County

City

State

Postal Code

Model Year
Manufacturer

Model

Electric Vehicle Type

Clean Alternative Fuel Vehicle (CAFV) Eligibility

Electric Range

Legislative District

DOL Vehicle ID

Vehicle Location

Electric Utility

2020 Census Tract

In [ ]:
#Import Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
#Load the Data Set from git hub

url ="https://raw.github.com/maha1606-gitoctocat/Electric-Vehicle-Population-Data-Analysis-using-Python/main/Dataset/Electric%20Vehicle%20Population%20Data.csv"

df = pd.read_csv(url)

# **Attributes and Description**


| S.No | Attribute                                             | Description                                                                            |
| ---- | ----------------------------------------------------- | -------------------------------------------------------------------------------------- |
| 1    | **VIN (Vehicle Identification Number)(1-10)**         | First 10 characters of the vehicle's VIN (unique vehicle identifier).                  |
| 2    | **County**                                            | County where the vehicle is registered.                                                |
| 3    | **City**                                              | City where the vehicle is registered.                                                  |
| 4    | **State**                                             | State of vehicle registration.                                                         |
| 5    | **Postal Code**                                       | ZIP/Postal code of the registered location.                                            |
| 6    | **Model Year**                                        | Manufacturing year of the electric vehicle.                                            |
| 7    | **Manufacturer**                                      | Company that manufactured the vehicle (e.g., Tesla, Nissan).                           |
| 8    | **Model**                                             | Model name of the electric vehicle.                                                    |
| 9    | **Electric Vehicle Type**                             | Type of EV (Battery Electric Vehicle (BEV) or Plug-in Hybrid Electric Vehicle (PHEV)). |
| 10   | **Clean Alternative Fuel Vehicle (CAFV) Eligibility** | Indicates whether the vehicle qualifies for CAFV incentives.                           |
| 11   | **Electric Range**                                    | Maximum distance the vehicle can travel on electric power (in miles).                  |
| 12   | **Legislative District**                              | Legislative district where the vehicle is registered.                                  |
| 13   | **DOL Vehicle ID**                                    | Unique vehicle identification number assigned by the Department of Licensing.          |
| 14   | **Vehicle Location**                                  | Geographic coordinates or registered location of the vehicle.                          |
| 15   | **Electric Utility**                                  | Electric utility provider serving the registered area.                                 |
| 16   | **2020 Census Tract**                                 | Census tract identifier based on the 2020 U.S. Census.                                 |

In [ ]:
df

,VIN (Vehicle Identification Number)(1-10),County,City,State,Postal Code,Model Year,Manufacturer,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,YV4H60PE7S,Kitsap,Bremerton,WA,98310.0,2025,VOLVO,XC90,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,32,23.0,277607004,POINT (-122.61136 47.5752),PUGET SOUND ENERGY INC,5.303508e+10
1,5YJ3E1EB3K,Snohomish,Lynnwood,WA,98087.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220,21.0,478641796,POINT (-122.27981 47.85727),PUGET SOUND ENERGY INC,5.306104e+10
2,1FADP5CUXD,Kitsap,Port Orchard,WA,98367.0,2013,FORD,C-MAX,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,19,35.0,253249678,POINT (-122.68471 47.50524),PUGET SOUND ENERGY INC,5.303509e+10
3,5YJSA1H20E,Thurston,Yelm,WA,98597.0,2014,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,208,2.0,131872905,POINT (-122.60735 46.94239),PUGET SOUND ENERGY INC,5.306701e+10
4,7SAYGDEE2P,Snohomish,Bothell,WA,98012.0,2023,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,1.0,260935657,POINT (-122.20105 47.84423),PUGET SOUND ENERGY INC,5.306105e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,JTMBDAFC4T,Clark,Vancouver,WA,98663.0,2026,SUBARU,SOLTERRA,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,49.0,288525583,POINT (-122.64695 45.65675),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...,5.301104e+10
1995,WVWKR7AU5K,King,Shoreline,WA,98133.0,2019,VOLKSWAGEN,E-GOLF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,125,32.0,447107615,POINT (-122.33364 47.73709),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303302e+10
1996,7SAYGDEF9N,Clark,Vancouver,WA,98682.0,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,17.0,198973316,POINT (-122.55149 45.69345),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...,5.301104e+10
1997,KNDCC3LG2N,Clark,Vancouver,WA,98683.0,2022,KIA,NIRO,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,18.0,208726766,POINT (-122.49212 45.60365),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...,5.301104e+10
1998,7SAYGAEE3N,King,Redmond,WA,98052.0,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,45.0,218856760,POINT (-122.13158 47.67858),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10

In [ ]:
# To evaluate data health, check for missing values, and monitor memory consumption.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 16 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   VIN (Vehicle Identification Number)(1-10)          1999 non-null   object
 1   County                                             1997 non-null   object
 2   City                                               1997 non-null   object
 3   State                                              1999 non-null   object
 4   Postal Code                                        1997 non-null   float64
 5   Model Year                                         1999 non-null   int64
 6   Manufacturer                                       1999 non-null   object
 7   Model                                              1999 non-null   object
 8   Electric Vehicle Type                              1999 non-null   object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  1999 non-null   object
 10  Electric Range                                     1999 non-null   int64
 11  Legislative District                               1996 non-null   float64
 12  DOL Vehicle ID                                     1999 non-null   int64
 13  Vehicle Location                                   1997 non-null   object
 14  Electric Utility                                   1997 non-null   object
 15  2020 Census Tract                                  1997 non-null   float64
dtypes: float64(3), int64(3), object(10)
memory usage: 250.0+ KB

In [ ]:
#to understand quick statistical summary of your DataFrame
df.describe()

,Postal Code,Model Year,Electric Range,Legislative District,DOL Vehicle ID,2020 Census Tract
count,1997.000000,1999.000000,1999.000000,1996.000000,1.999000e+03,1.997000e+03
mean,98227.921883,2021.628814,54.506753,31.646794,2.399679e+08,5.301300e+10
std,402.162435,3.318931,89.962737,14.742841,7.142224e+07,1.096847e+09
min,85364.000000,2011.000000,0.000000,1.000000,1.593721e+06,4.027001e+09
25%,98033.000000,2020.000000,0.000000,20.000000,2.081384e+08,5.303301e+10
50%,98115.000000,2023.000000,0.000000,36.000000,2.602226e+08,5.303302e+10
75%,98366.000000,2024.000000,53.000000,45.000000,2.801624e+08,5.303509e+10
max,99362.000000,2027.000000,337.000000,49.000000,4.786418e+08,5.307794e+10

In [ ]:
# displaying first 5 rows
df.head(5)

,VIN (Vehicle Identification Number)(1-10),County,City,State,Postal Code,Model Year,Manufacturer,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,YV4H60PE7S,Kitsap,Bremerton,WA,98310.0,2025,VOLVO,XC90,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,32,23.0,277607004,POINT (-122.61136 47.5752),PUGET SOUND ENERGY INC,5.303508e+10
1,5YJ3E1EB3K,Snohomish,Lynnwood,WA,98087.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220,21.0,478641796,POINT (-122.27981 47.85727),PUGET SOUND ENERGY INC,5.306104e+10
2,1FADP5CUXD,Kitsap,Port Orchard,WA,98367.0,2013,FORD,C-MAX,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,19,35.0,253249678,POINT (-122.68471 47.50524),PUGET SOUND ENERGY INC,5.303509e+10
3,5YJSA1H20E,Thurston,Yelm,WA,98597.0,2014,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,208,2.0,131872905,POINT (-122.60735 46.94239),PUGET SOUND ENERGY INC,5.306701e+10
4,7SAYGDEE2P,Snohomish,Bothell,WA,98012.0,2023,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,1.0,260935657,POINT (-122.20105 47.84423),PUGET SOUND ENERGY INC,5.306105e+10

In [ ]:
#to understand the attribute and to check  the column labels
df.columns

Index(['VIN (Vehicle Identification Number)(1-10)', 'County', 'City', 'State',
       'Postal Code', 'Model Year', 'Manufacturer', 'Model',
       'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range',
       'Legislative District', 'DOL Vehicle ID', 'Vehicle Location',
       'Electric Utility', '2020 Census Tract'],
      dtype='object')

In [ ]:
df.dtypes

VIN (Vehicle Identification Number)(1-10)             object
County                                                object
City                                                  object
State                                                 object
Postal Code                                          float64
Model Year                                             int64
Manufacturer                                          object
Model                                                 object
Electric Vehicle Type                                 object
Clean Alternative Fuel Vehicle (CAFV) Eligibility     object
Electric Range                                         int64
Legislative District                                 float64
DOL Vehicle ID                                         int64
Vehicle Location                                      object
Electric Utility                                      object
2020 Census Tract                                    float64
dtype: object

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

VIN (Vehicle Identification Number)(1-10)            0
County                                               2
City                                                 2
State                                                0
Postal Code                                          2
Model Year                                           0
Manufacturer                                         0
Model                                                0
Electric Vehicle Type                                0
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0
Electric Range                                       0
Legislative District                                 3
DOL Vehicle ID                                       0
Vehicle Location                                     2
Electric Utility                                     2
2020 Census Tract                                    2
dtype: int64